# Lab 1A: Data, Code & Google Colab

The first step is to import your library pandas and assign it to an alias "pd"

In [0]:
import pandas as  pd

The next step is for you to import your data!  Luckly, it's hosted on GitHub.  Use the read_csv() function to import that good ol' data

In [0]:
cdc = pd.read_csv("https://raw.githubusercontent.com/nschettini/datasets/master/cdc.csv")

Lets take a look at your data (this is the "first" question on your Lab Sheet that's in Google Classroom

In [47]:
cdc

       Unnamed: 0           age  ...              drink_water sunburns
0               1  16 years old  ...           1 time per day  0 times
1               2  16 years old  ...          2 times per day  0 times
2               3  17 years old  ...  4 or more times per day  2 times
3               4  17 years old  ...           1 time per day  0 times
4               5  16 years old  ...  4 or more times per day  1 times
...           ...           ...  ...                      ...      ...
15619       15620  15 years old  ...                      NaN      NaN
15620       15621  15 years old  ...                      NaN      NaN
15621       15622  17 years old  ...                      NaN      NaN
15622       15623  15 years old  ...                      NaN      NaN
15623       15624  15 years old  ...                      NaN      NaN

[15624 rows x 34 columns]

Now, follow each question on the lab.  You can answer the questions in the word document, or, if you want, modify this document with the answers.

In [44]:
cdc

       Unnamed: 0           age  ...              drink_water sunburns
0               1  16 years old  ...           1 time per day  0 times
1               2  16 years old  ...          2 times per day  0 times
2               3  17 years old  ...  4 or more times per day  2 times
3               4  17 years old  ...           1 time per day  0 times
4               5  16 years old  ...  4 or more times per day  1 times
...           ...           ...  ...                      ...      ...
15619       15620  15 years old  ...                      NaN      NaN
15620       15621  15 years old  ...                      NaN      NaN
15621       15622  17 years old  ...                      NaN      NaN
15622       15623  15 years old  ...                      NaN      NaN
15623       15624  15 years old  ...                      NaN      NaN

[15624 rows x 34 columns]